baseURL: "/"
languageCode: "en"
title: "facundo.dev"
theme: "hugo-xmin"
pygmentsStyle: "trac"
pygmentsUseClasses: true
pygmentsCodeFences: true
pygmentsCodefencesGuessSyntax: true
pygmentsUseClassic: true
pygmentOptions: "linenos=inline"
relativeUrls: true

params:
  mainSections: ["post","posts"]
  title: "facundo.dev"
  footer: >
    [Github](https://github.com/facundomedica) | [Twitter](https://twitter.com/facundomedica) | [LinkedIn](https://www.linkedin.com/in/fmedica/) | [My resume](https://facundo.dev/Facundo_Medica_CV_may2022.pdf)
    

    &copy; Facundo Medica 2019 -- {Year}
permalinks:
  note: "/note/:year/:month/:day/:slug/"
  posts: "/posts/:year/:month/:day/:slug/"

author:
  name: "Facundo Medica"
  website: "https://facundo.dev"
  email: "facundomedica@protonmail.com"
  github: "facundomedica"
  linkedin: "facundo-medica"
  stackoverflow: "users/5240559/facumedica"

menu:
  main:
    - name: home
      url: ""
      weight: 1
    - name: about
      url: "about/"
      weight: 2
    # - name: Categories
    #   url: "categories/"
    #   weight: 3
    - name: tags
      url: "tags/"
      weight: 40