baseURL: "/"
languageCode: "en"
title: "facundo.dev"
theme: "hugo-xmin"
pygmentsStyle: "trac"
pygmentsUseClasses: true
pygmentsCodeFences: true
pygmentsCodefencesGuessSyntax: true
pygmentsUseClassic: true
pygmentOptions: "linenos=inline"
relativeUrls: true

params:
  mainSections: ["post","posts"]
  title: "facundo.dev"
  footer: >
    [Github](https://github.com/facundomedica) | [Twitter](https://twitter.com/facundomedica) | [LinkedIn](https://www.linkedin.com/in/fmedica/) | [My resume](https://facundo.dev/Facundo_Medica_CV_may2022.pdf)
    

    &copy; Facundo Medica 2019 -- {Year}

author:
  name: "Facundo Medica"
  website: "https://facundo.dev"
  email: "facundomedica@protonmail.com"
  github: "facundomedica"
  linkedin: "facundo-medica"
  stackoverflow: "users/5240559/facumedica"
